language: python

python:
    - "2.7"
    - "3.5"

before_install:
    - pip install -U pip
    - pip install pytest pytest-cov
    - pip install coveralls

install:
    - pip install -e .

script:
    - py.test

after_success:
    # Run coveralls only once, not once for each Python release
    - if [[ $ENV == python=3.5* ]]; then
          coveralls;
      fi

