language: python

python:
    - "2.7"
    - "3.5"

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
    - pip install -e .

script:
    - py.test

after_success:
    - coveralls
